name: GitHub Classroom Workflow

on: [ push ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: List Files in Android SDK
        run: ls -lah $HOME/.android/sdk
      - name: Check PATH
        run: echo $PATH
      - name: Add Android SDK Path
        run: echo "sdk.dir=$HOME/.android/sdk" >> './local.properties'
      - uses: education/autograding@v1
