name: GitHub Classroom Workflow

on: [ push ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Gradle Wrapper
        run: $SHELL gradle_wrapper.sh
      - name: Add Android SDK Path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" >> './local.properties'
      - uses: education/autograding@v1
