name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check gradle Command
        run: which gradle
      - name: Add Android SDK Path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" >> './local.properties'
      - uses: education/autograding@v1
