name: GitHub Classroom Workflow

on: [ push ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Add Android SDK Path
        run: echo "sdk.dir=$HOME/.android/sdk" >> '$HOME/work/course-project-group-80/course-project-group-80/local.properties'
      - name: CHeck Properties File
        run: cat ./local.properties
      - uses: education/autograding@v1
